// Code generated by protoc-gen-go. DO NOT EDIT.
// source: time.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TimeReq struct {
	Cmd                  uint32   `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeReq) Reset()         { *m = TimeReq{} }
func (m *TimeReq) String() string { return proto.CompactTextString(m) }
func (*TimeReq) ProtoMessage()    {}
func (*TimeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{0}
}

func (m *TimeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeReq.Unmarshal(m, b)
}
func (m *TimeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeReq.Marshal(b, m, deterministic)
}
func (m *TimeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeReq.Merge(m, src)
}
func (m *TimeReq) XXX_Size() int {
	return xxx_messageInfo_TimeReq.Size(m)
}
func (m *TimeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeReq.DiscardUnknown(m)
}

var xxx_messageInfo_TimeReq proto.InternalMessageInfo

func (m *TimeReq) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

type TimeRes struct {
	Time                 string   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	GMT                  string   `protobuf:"bytes,2,opt,name=GMT,proto3" json:"GMT,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeRes) Reset()         { *m = TimeRes{} }
func (m *TimeRes) String() string { return proto.CompactTextString(m) }
func (*TimeRes) ProtoMessage()    {}
func (*TimeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{1}
}

func (m *TimeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRes.Unmarshal(m, b)
}
func (m *TimeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRes.Marshal(b, m, deterministic)
}
func (m *TimeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRes.Merge(m, src)
}
func (m *TimeRes) XXX_Size() int {
	return xxx_messageInfo_TimeRes.Size(m)
}
func (m *TimeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRes.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRes proto.InternalMessageInfo

func (m *TimeRes) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *TimeRes) GetGMT() string {
	if m != nil {
		return m.GMT
	}
	return ""
}

func init() {
	proto.RegisterType((*TimeReq)(nil), "protocol.TimeReq")
	proto.RegisterType((*TimeRes)(nil), "protocol.TimeRes")
}

func init() { proto.RegisterFile("time.proto", fileDescriptor_49a92d779a28c7fd) }

var fileDescriptor_49a92d779a28c7fd = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc9, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0xd2, 0x5c,
	0xec, 0x21, 0x99, 0xb9, 0xa9, 0x41, 0xa9, 0x85, 0x42, 0x02, 0x5c, 0xcc, 0xc9, 0xb9, 0x29, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x20, 0xa6, 0x92, 0x3e, 0x4c, 0xb2, 0x58, 0x48, 0x88, 0x8b,
	0x05, 0xa4, 0x1f, 0x2c, 0xcb, 0x19, 0x04, 0x66, 0x83, 0x34, 0xb8, 0xfb, 0x86, 0x48, 0x30, 0x81,
	0x85, 0x40, 0xcc, 0x24, 0x36, 0xb0, 0xb9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xa6,
	0xb4, 0x63, 0x6c, 0x00, 0x00, 0x00,
}
